services:
  # MongoDB Service
  mongo_db:
    image: mongo:6-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  # Node API Service
  api:
    build: .
    ports:
      - 8420:8420
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 8420
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      SECRET: foobar
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
