GET http://localhost:8420/v1/notes

POST http://localhost:8420/v1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoZXNzX3BsYXllciIsImlkIjoiNjViOTM3ZjJjMTU0ZTcwZDE2MmM5ODY0IiwiaWF0IjoxNzA2NjM3MzQ4LCJleHAiOjE3MDY2NDA5NDh9.9XBqckO2QtocT-fOYSIn9Wg7eacCMPzNkWIUYBGxsTE

{
    "content": "forreal? the first note",
    "important": true
}
