GET http://localhost:8420/v1/notes

GET http://localhost:8420/v1/notes/65b93ce35f313b07af9b57ca

POST http://localhost:8420/v1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpYmJsZSIsImlkIjoiNjViYmYzYzg4NWQ4ZTM4Y2JmMTY5YjRiIiwiaWF0IjoxNzA2ODE2NDcyLCJleHAiOjE3MDY4MjAwNzJ9.AyeRasWKjJVCEgY6ChC46ymlCSs2skO2elMTYFFfP9U

{
    "content": "wiggle",
    "important": true
}
