GET http://localhost:8420/v1/users

POST http://localhost:8420/v1/users
Content-Type: application/json

{
    "name": "admin",
    "username": "admin",
    "password": "admin"
}

PUT http://localhost:8420/v1/users/65c1a327dfd1700cb9e2e728
Content-Type: application/json

{
    "name": "testy",
    "username": "tester",
    "password": "tester"
}

DELETE http://localhost:8420/v1/users/65c1a327dfd1700cb9e2e728
Content-Type: application/json
