name: frontend test runner 

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
    branches: [main, issue-61]
    types: [opened, synchronize]

jobs:
  frontend_test_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        working-directory: ./frontend
        run: npm install
      - name: lint 
        working-directory: ./frontend
        run: npm run lint
      - name: tests
        working-directory: ./backend
        run: npm run test

