name: pipeline

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    branches: [main, issue-45]
    types: [opened, synchronize]

jobs:
  backend_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker compose up -d
      - name: Test
        run: docker compose exec api npm run lint
